### ISSUE TITLE
PHP errors generated in Checkout SDK mode

### ISSUE THREAD

**Issue by gbakeman** [Nuvei/nuvei-plugin-woocommerce#3]
While the plugin is set to Checkout SDK, we experience the following error whenever the Nuvei DMN client tries to access the Notify URL. This occasionally causes an error to generate orders in our system, whether the transaction was declined or accepted. When the plugin is set to Cashier mode, the errors no longer seem to be generated.

```
[30-Mar-2024 19:18:04 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Nuvei_String::get_notify_url(), 0 passed in /public_html/wp-content/plugins/nuvei-plugin-woocommerce/includes/class-nuvei-notify-url.php on line 484 and at least 1 expected in /public_html/wp-content/plugins/nuvei-plugin-woocommerce/includes/class-nuvei-string.php:19
Stack trace:
#0 /public_html/wp-content/plugins/nuvei-plugin-woocommerce/includes/class-nuvei-notify-url.php(484): Nuvei_String::get_notify_url()
#1 /public_html/wp-content/plugins/nuvei-plugin-woocommerce/includes/class-nuvei-notify-url.php(424): Nuvei_Notify_Url->create_auto_void('Sale')
#2 /public_html/wp-content/plugins/nuvei-plugin-woocommerce/includes/class-nuvei-notify-url.php(175): Nuvei_Notify_Url->get_order_by_trans_id([trnsid], 'Sale')
#3 /public_html/wp-content/plugins/nuvei-plugin-woocomm in /public_html/wp-content/plugins/nuvei-plugin-woocommerce/includes/class-nuvei-string.php on line 19
```

Related log output:
> 2024-03-30T19:17:46.957835+00:00    INFO    [GUID?] wooCommerce Plugin 2.1.0|class-nuvei-notify-url.php|20    DMN params    {"Request params":{"wc-api":"nuvei_listener","ppp_status":"FAIL","Status":"DECLINED", ... further info ..."REQUEST_METHOD":"POST","HTTP_USER_AGENT":"Apache-HttpClient\/4.5 (Java\/1.8.0_322)"}
> 2024-03-30T19:17:49.958459+00:00    INFO    [GUID?] wooCommerce Plugin 2.1.0|class-nuvei-notify-url.php|173    SDK Order
> 2024-03-30T19:17:49.958795+00:00    INFO    [GUID?]    wooCommerce Plugin 2.1.0|class-nuvei-notify-url.php|405    get_order_by_trans_id    [[transid],"Sale"]
> 2024-03-30T19:18:04.964184+00:00    INFO    [GUID?]    wooCommerce Plugin 2.1.0|class-nuvei-notify-url.php|460    create_auto_void    [[unknown number A],"Sale",[unknowwn number B]]

**Comment by miroslav-sc** [comment]
Please, check with the latest version!
