### ISSUE TITLE
Payment option does not appear after having configured the plugin

### ISSUE THREAD

**Issue by mrflo** [Nuvei/nuvei-plugin-woocommerce#4]
Wordpress Version 6.5.2, 
Woocommerce 8.7.0

The option to pay with Nuvei is not appearing but the assets are well loaded (css,js) 
In the logs we have the infiormation that the product data are loaded correctly and then nothing, no errors logged.

```
2024-04-10T19:58:23.733395+00:00    INFO    f60dc0c0579d9670dc5c2f6586d28724    wooCommerce Plugin 2.1.0|abstract-nuvei-request.php|709    get_products_data() data    {
    "wc_subscr": false,
    "subscr_data": [],
    "products_data": [
        {
            "product_id": 24872,
            "quantity": 1,
            "price": "9",
            "name": "Product NAME",
            "in_stock": true,
            "item_id": "b6e61f3a46000af53590f293dcf35c20"
        }
    ],
    "totals": {
        "subtotal": "9",
        "subtotal_tax": 0,
        "shipping_total": "0",
        "shipping_tax": 0,
        "shipping_taxes": [],
        "discount_total": 0,
        "discount_tax": 0,
        "cart_contents_total": "9",
        "cart_contents_tax": 0,
        "cart_contents_taxes": {
            "1": 0
        },
        "fee_total": "0",
        "fee_tax": 0,
        "fee_taxes": [],
        "total": "9.00",
        "total_tax": 0
    }
}
```

Payment page is Cashier
Sync Payment Plans button does say success in the log.

Can you let me know what could be the problem?  
When and on what conditions the payment gateway is hidden from the payment options ?

UPDATE: I tried the dev 3.0 branch and the payment is showing but it goes straight to a confirmation page.
Is there a plan to finish the release the dev branch soon ?

**Comment by mrflo** [comment]
@miroslav-sc @spantaleevaxtc Are you guys still working on the plugin to make it work on latest versions ? What are the plans? 
I need to know if I need to swap to another way to implement it. Thanks

**Comment by miroslav-sc** [comment]
Our QA colleague testing at the moment version 3.0.0, but will need at least a day to finish. We will create new release if everything is OK.
Regards!

**Comment by mrflo** [comment]
Thanks @miroslav-sc for the quick answer 👍

**Comment by mrflo** [comment]
Hi @miroslav-sc do you have any news on when the new release will be ready ?  Thanks in advance!

**Comment by miroslav-sc** [comment]
There were few problems to clean. Tests are running at the moment.

**Comment by mrflo** [comment]
Hi @miroslav-sc Any updates on the status of the tests. It seems I don't see any commits. May be we can test for you as well if you publish the latest version ?

**Comment by miroslav-sc** [comment]
Hi, the tests are OK, but we made them on WC 8.8.2, now there is v8.8.3. The QA team will run the tests again today on this version and if there are no problems a new version will be released.
