### ISSUE TITLE
JS error "Automatic publicPath is not supported in this browser" in version 3.0.1

### ISSUE THREAD

**Issue by gbakeman** [Nuvei/nuvei-plugin-woocommerce#6]
Similar to issue #5, there's an incompatibility introduced, this time [between updates 3.0.0 and 3.0.1](https://github.com/Nuvei/nuvei-plugin-woocommerce/compare/v3.0.0...v3.0.1), with [WooCommerce Points & Rewards](https://woocommerce.com/products/woocommerce-points-and-rewards/) v1.8.5 and potentially other plugins (see below). When loading the Checkout page for the first time, this error is printed to the browser console: 

```
Uncaught Error: Automatic publicPath is not supported in this browser
    <anonymous> /checkout/ line 2 > injectedScript:38
    <anonymous> /checkout/ line 2 > injectedScript:38
    <anonymous>/checkout/ line 2 > injectedScript:45
    jQuery 13
    <anonymous> /wp-content/plugins/nuvei-plugin-woocommerce/assets/js/nuvei_public.js?ver=1:311
    jQuery 13
line 2 > injectedScript:38:5685
```

If I try to click the Continue button to go to the payment details screen, I see this: 

```
Uncaught ReferenceError: simplyConnect is not defined
    showNuveiCheckout /wp-content/plugins/nuvei-plugin-woocommerce/assets/js/nuvei_public.js?ver=1:175
    <anonymous> /checkout/ line 2 > injectedScript:1
    jQuery 3
    submit_error /wp-content/plugins/woocommerce/assets/js/frontend/checkout.min.js?ver=9.0.0:1
    success /wp-content/plugins/woocommerce/assets/js/frontend/checkout.min.js?ver=9.0.0:1
    jQuery 8
    submit /wp-content/plugins/woocommerce/assets/js/frontend/checkout.min.js?ver=9.0.0:1
    jQuery 10
    init /wp-content/plugins/woocommerce/assets/js/frontend/checkout.min.js?ver=9.0.0:1
    <anonymous> /wp-content/plugins/woocommerce/assets/js/frontend/checkout.min.js?ver=9.0.0:1
    jQuery 13
nuvei_public.js:175:2
```
However, unlike the last issue, this one is not easily resolved by changing the checkout mode - it occurs with Checkout SDK and cashier modes. I hope there's still something that can be done on this side to resolve the incompatibility with WooCommerce's Points & Rewards.

**Comment by odeland** [comment]
We had the same problem in production. Nobody was able to checkout using Nuvei Checkout. We do not have WooCommerce's Points & Rewards plugin installed. The same JavaScript errors posted above come up in the browser's console. We had to revert back to version 3.0.0 of the plugin.

**Comment by gbakeman** [comment]
@odeland Thanks for confirming so I know it's not just me! It's interesting to find that you don't have the same plugin as me. Do you think you might have the time to test and isolate which, if any, plugin Nuvei may be conflicting with? I've been able to restore normal functionality by disabling the conflicting plugin on my end. I also want to recommend that you reach out to the Nuvei Integration Support team at integration-international@nuvei.com. They've been assisting me with integration and also interfacing with the developers who manage this plugin.

**Comment by miroslav-sc** [comment]
I am sorry for the problem, but it is impossible to test our plugin how behave with all available plugins for Wordpress/Woocommerce.
The only plugins we test for compatibility are mentioned in the [documentation](https://docs.nuvei.com/documentation/plugins-docs/woocommerce/#integration-with-other-plugins).
I will report you problem, but cannot promise it will be solved.

**Comment by miroslav-sc** [comment]
Guys, I checked Points & Rewards plugin with our plugin v3.0.3 and wasn't able to reproduce the problem.
Can you also check and send feedback if the problem was solved?

**Comment by gbakeman** [comment]
@miroslav-sc It looks like you've fixed the incompatibility with WC P&R and full Checkout SDK is now working, thank you!
