### ISSUE TITLE
v3.2.3 release does not upgrade (replace) previous plugin version

### ISSUE THREAD

**Issue by gbakeman** [Nuvei/nuvei-plugin-woocommerce#8]
Hi miroslav,

Thanks for the latest update. I've tried installing it today, however WordPress adds it as a new plugin (with fatal error on activation) instead of replacing the previous version of the plugin.

**Comment by miroslav-sc** [comment]
Hi!

I am sorry for the problem! Looks like there was some problem and the third file in the release was not uploaded.
Probably you downloaded some of the other archives and tried to install directly?
To solve the problem remove the last installed plugin (the new one), go to release v3.2.3 and download nuvei-plugin-woocommerce.zip which I just added. It have to replace the old plugin as usually.

Regards!

**Comment by gbakeman** [comment]
I saw you just uploaded the release ZIP - I went ahead and downloaded that, and tried the same update procedure as last time which worked. Thanks for your fast response!
